services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
  web:
    container_name: web
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./web:/app
    expose:
      - 3000
    environment:
      - WDS_SOCKET_PORT=0
  posts:
    container_name: posts
    build: 
      context: ./posts
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./posts:/app
    expose:
      - 5000
    environment:
      - EVENT_BUS_API_ORIGIN=http://event-bus:5000
      - POSTS_PORT=5000
  comments:
    container_name: comments
    build: 
      context: ./comments
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./comments:/app
    expose:
      - 5000
    environment:
      - EVENT_BUS_API_ORIGIN=http://event-bus:5000
      - COMMENTS_PORT=5000
  querys:
    container_name: querys
    depends_on:
      - event-bus
    build: 
      context: ./querys
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./querys:/app
    expose:
      - 5000
    environment:
      - EVENT_BUS_API_ORIGIN=http://event-bus:5000
      - QUERYS_PORT=5000
  event-bus:
    container_name: event-bus
    build: 
      context: ./event-bus
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./event-bus:/app
    environment:
      - POST_API_ORIGIN=http://posts:5000
      - COMMENT_API_ORIGIN=http://comments:5000
      - QUERY_API_ORIGIN=http://querys:5000
      - MODERATION_API_ORIGIN=http://moderation:5000
      - EVENT_BUS_PORT=5000
  moderation:
    container_name: moderation
    build: 
      context: ./moderation
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./moderation:/app
    environment:
      - POST_API_ORIGIN=http://posts:5000
      - COMMENT_API_ORIGIN=http://comments:5000
      - QUERY_API_ORIGIN=http://querys:5000
      - EVENT_BUS_API_ORIGIN=http://event-bus:5000
      - MODERATION_PORT=5000
