apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: moderation
  template:
    metadata:
      labels:
        component: moderation
    spec:
      containers:
        - name: moderation
          image: kwangdock/k8s-docker-simple-blog-moderation
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: POST_API_ORIGIN
              value: http://posts-service:5000
            - name: COMMENTS_API_ORIGIN
              value: http://comments-service:5000
            - name: QUERY_API_ORIGIN
              value: http://querys-service:5000
            - name: EVENT_BUS_API_ORIGIN
              value: http://event-bus-service:5000
            - name: MODERATION_PORT
              value: "5000"
